name: Claude — Shared PR Review (inline)

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch for comparison"
        required: false
        type: string
        default: main
      prompt:
        description: "Optional extra guidance for the review"
        required: false
        type: string
      model:
        description: "Anthropic model"
        required: false
        type: string
        default: claude-sonnet-4-20250514
      mcp_config:
        description: "Path or JSON for MCP config (merged with GitHub MCP)"
        required: false
        type: string
        default: .github/claude/mcp.json
      allowed_tools:
        description: "Allowed tools list (pipe-separated)"
        required: false
        type: string
        default: |
          WebSearch
          WebFetch
          Bash(find:*)
          Bash(grep:*)
          Bash(ls:*)
          Bash(cat:*)
          Bash(head:*)
          Bash(tail:*)
          Bash(wc:*)
          Bash(tree:*)
          Bash(gh label:*)
          Bash(gh issue:*)
          Bash(gh project:*)
          mcp__context7__resolve-library-id
          mcp__context7__get-library-docs
          mcp__godoc-mcp__get_doc
          mcp__bloom__search_code
      disallowed_tools:
        description: "Disallowed tools list (pipe-separated)"
        required: false
        type: string
        default: |
          Edit
          MultiEdit
          NotebookEdit
          Write
      runner:
        description: "GitHub runner to use"
        required: false
        type: string
        default: blacksmith-8vcpu-ubuntu-2204
      tech_stack:
        description: "Technology stack (go, nodejs, python, etc)"
        required: false
        type: string
        default: go
    secrets:
      ANTHROPIC_API_KEY:
        required: true
      BLOOM_MCP_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  review:
    name: Inline review
    runs-on: ${{ inputs.runner }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.js (if needed)
        if: inputs.tech_stack == 'nodejs'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm (if needed)
        if: inputs.tech_stack == 'nodejs'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Claude inline PR review
        uses: anthropics/claude-code-action@main
        env:
          DEFAULT_WORKFLOW_TOKEN: ${{ github.token }}
          BLOOM_MCP_TOKEN: ${{ secrets.BLOOM_MCP_TOKEN }}
        with:
          mode: experimental-review
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: ${{ inputs.model }}
          base_branch: ${{ inputs.base_branch }}
          allowed_tools: ${{ inputs.allowed_tools }}
          disallowed_tools: ${{ inputs.disallowed_tools }}
          direct_prompt: |
            You are conducting a comprehensive code review for a **production-grade** ${{ inputs.tech_stack }}-based application.
            
            **Production-Grade Requirements:**
            - Code must be ready for deployment to production environments
            - Ensure robust error handling and recovery mechanisms
            - Verify proper logging and monitoring capabilities
            - Check for scalability and performance under load
            - Validate security hardening and defense in depth
            - Confirm backward compatibility and migration paths
            - Ensure observability (metrics, traces, logs)
            
            **Your Review Scope:**
            - Analyze the entire package holistically, not just isolated files
            - Focus on the changes in this PR, but consider their impact on the broader codebase
            - Review architecture, code quality, security, performance, and maintainability
            - Perform comprehensive security analysis including OWASP Top 10 vulnerabilities
            - Check for secure coding practices and potential attack vectors
            - Conduct semantic linting: check spelling, grammar, word choice, and terminology consistency
            - Verify clear and professional technical communication in comments and documentation

            **Feedback Categories:**
            Provide feedback in exactly 3 categories with these specific emojis:

            **Critical ❌** - Issues that MUST be fixed before merge:
            - Security vulnerabilities (SQL injection, XSS, CSRF, insecure crypto, exposed secrets)
            - Authentication/authorization bypass
            - Input validation failures
            - Potential panics or crashes (Go) / unhandled exceptions (Node.js)
            - Breaking changes to public APIs
            - Data corruption risks
            - Memory leaks
            - Race conditions
            - Missing critical error handling
            - Production stability risks
            - Data loss scenarios

            **Minor 🟡** - Important improvements that should be addressed:
            - Performance inefficiencies
            - Error handling improvements
            - Design pattern violations
            - Missing tests for critical paths
            - Documentation gaps for public APIs
            - Potential bugs that don't cause crashes
            - Insufficient logging for production debugging
            - Missing retry logic for transient failures
            - Inadequate input sanitization
            - Spelling mistakes and typos in comments, docs, and strings
            - Grammar and language clarity issues
            - Inconsistent terminology usage

            **Nits 🟢** - Style and best practice suggestions:
            - Code style inconsistencies
            - Naming improvements
            - Minor refactoring opportunities
            - Comment clarity and readability
            - Test coverage for edge cases
            - Word choice and semantic clarity improvements
            - Technical writing style enhancements
            - Consistent use of technical terms and domain language

            ${{ inputs.tech_stack == 'go' && '
            **Go-Specific Production Review Principles:**
            1. **Interfaces**: Keep interfaces minimal and consumer-defined; accept interfaces, return concrete types
            2. **Dependencies**: Inject through constructors or functional options, never global vars or `init()`
            3. **Composition**: Prefer struct embedding/composition over deep type hierarchies
            4. **Error Handling**: Handle errors early, no hidden panics, use error wrapping for context
            5. **Concurrency**: Check for goroutine leaks, proper context cancellation, safe concurrent access
            6. **Resource Management**: Verify proper defer usage, connection pooling, graceful shutdown
            7. **Dead Code**: Identify and flag unused functions or dead code
            8. **DDD Architecture**: Ensure proper layer separation (domain, infrastructure, services, presentation) if applicable
            9. **Go Idioms**: Follow standard Go conventions and best practices
            10. **Production Readiness**: Ensure proper metrics, health checks, and graceful degradation
            ' || '' }}

            ${{ inputs.tech_stack == 'iota-sdk' && '
            **IOTA SDK-Specific Production Review Principles:**
            1. **Dependency Inversion Principle**:
               - Check for proper interface usage following Go best practices
               - Accept interfaces, return concrete types
               - Define interfaces where they are used (consumer-side), not where implemented
               - Prefer small, focused interfaces (interface segregation)
               - Identify places where concrete types could be replaced with interfaces for better testability
               - Ensure dependencies flow from concrete implementations to abstractions, not vice versa
            2. **SQL Query Management**:
               - All SQL queries MUST be defined as constants at the top of repository files
               - Use descriptive names like `paymentFindQuery`, `userInsertQuery`, etc.
               - NEVER write inline SQL strings in functions
            3. **SQL Construction**: 
               - Use `pkg/repo` package for SQL construction (Join, JoinWhere, Insert, Update, FormatLimitOffset)
               - NEVER concatenate SQL strings manually
               - Use parameterized queries to prevent SQL injection
            4. **Test Data Management**:
               - NO raw SQL statements in tests - only use repository methods for inserts/updates
               - Use repository pattern for all test data setup and teardown
               - Tests should use the same repository interfaces as production code
            5. **HTMX Workflows**:
               - Use `pkg/htmx` package for all HTMX header operations
               - Use helper functions: `htmx.IsHxRequest()`, `htmx.Redirect()`, `htmx.SetTrigger()`, etc.
               - NEVER check HTMX headers directly with `r.Header.Get("Hx-*")`
            6. **Repository Pattern**:
               - Follow strict repository pattern with clear separation of concerns
               - Domain layer defines repository interfaces
               - Infrastructure layer implements repositories
               - Services orchestrate business logic using repositories
            7. **DDD Architecture**: 
               - Ensure strict layer separation (domain, infrastructure, services, presentation)
               - Domain must not depend on infrastructure
               - Use dependency injection through constructors
            8. **Templ Templates**:
               - Use .templ files for HTML generation, not string concatenation
               - Follow existing component patterns in components/ package
               - Run templ generate after modifications
            9. **Error Handling**:
               - Use `pkg/serrors` for standard error types
               - Wrap errors with context using error wrapping
               - Handle errors at appropriate layers
            10. **Go Idioms**: Follow standard Go conventions and best practices
            11. **Production Readiness**: Ensure proper metrics, health checks, logging, and graceful degradation
            ' || '' }}

            ${{ inputs.tech_stack == 'nodejs' && '
            **Node.js/JavaScript-Specific Production Review Principles:**
            1. **Async/Await**: Ensure proper async error handling, no unhandled promise rejections
            2. **Type Safety**: If TypeScript, verify proper typing and avoid `any` type
            3. **Dependencies**: Check for security vulnerabilities in npm packages, verify lock files
            4. **Memory Management**: Watch for closures that might cause memory leaks, check heap usage patterns
            5. **Error Boundaries**: Ensure proper error handling and recovery mechanisms
            6. **Input Validation**: Validate and sanitize all user inputs, prevent injection attacks
            7. **Framework Best Practices**: Follow conventions for Express/Next.js/etc.
            8. **Module Patterns**: Use appropriate module patterns (CommonJS/ESM)
            9. **Event Loop**: Avoid blocking operations, ensure proper async patterns
            10. **Production Readiness**: Verify clustering/PM2 config, health endpoints, graceful shutdown
            ' || '' }}

            **Output Format:**
            Structure your review as follows:
            ```
            ## Code Review Summary
            Brief overview of the changes and overall assessment.

            ### Critical ❌
            - [Specific issue with file:line reference]

            ### Minor 🟡  
            - [Important improvement needed]

            ### Nits 🟢
            - [Style or best practice suggestion]

            ## Architecture Notes
            [Any observations about design patterns or architectural concerns]

            ## Security Considerations
            [Security analysis covering relevant security aspects]

            ## Performance Notes
            [Any performance-related observations]

            ## Language & Documentation Quality
            [Spelling, grammar, terminology consistency assessment]
            ```

            **Important**: 
            - Always include file:line references for specific issues
            - If no issues exist in a category, write "None identified"
            - Focus on actionable feedback
            - Be constructive and educational in your comments
            - Review only the changed lines/hunks in this PR
            - Prefer **inline comments** tied to exact lines
            - Use GitHub's suggestion blocks for quick fixes

            ${{ inputs.prompt }}
          mcp_config: ${{ inputs.mcp_config }}